---
- hosts: edge
  gather_facts: false
  connection: network_cli

  tasks:
    - name: set host & domain names
      ansible.netcommon.cli_config:
        config: |
          set system host-name router
          set system domain-name {{ domain }}
          set system ip override-hostname-ip 192.168.1.1
          set system offload hwnat enable

    - name: Set up DNS
      community.network.edgeos_config:
        src: dns.j2
      tags: dns

    - name: Set up DHCP
      community.network.edgeos_config:
        src: dhcp.j2
      tags: dhcp

    - name: Set up DHCPv6-PD
      community.network.edgeos_config:
        src: dhcpv6.j2
      tags: dhcp

    - name: Set other DHCP lines
      ansible.netcommon.cli_config:
        config: |
          set service dhcp-server shared-network-name LAN subnet 192.168.1.0/24 domain-name {{ domain }}
          set service dhcp-server shared-network-name LAN subnet 192.168.1.0/24 unifi-controller 192.168.1.{{ unifi.ip_address }}

    - name: Set port forwarding rules
      community.network.edgeos_config:
        src: port-forwards.j2

    - name: Set firewalls
      community.network.edgeos_config:
        src: firewall.j2

    - name: Define vlans
      community.network.edgeos_config:
        src: vlans.j2
