---
- hosts: edge
  gather_facts: no
  connection: network_cli

  tasks:
    - name: set host & domain names
      cli_config:
        config:
          - set system host-name router
          - set system domain-name {{ domain }}
          - set system ip override-hostname-ip 192.168.1.1

    - name: Set up DNS
      cli_config:
        config: "{{ lookup('template', 'dns.j2') }}"

    - name: Set up DHCP
      cli_config:
        config: "{{ lookup('template', 'dhcp.j2') }}"

    - name: Set other DHCP lines
      cli_config:
        config:
          - set service dhcp-server shared-network-name LAN subnet 192.168.1.0/24 domain-name {{ domain }}
          - set service dhcp-server shared-network-name LAN subnet 192.168.1.0/24 unifi-controller 192.168.1.{{ unifi.ip_address }}

    - name: Set port forwarding rules
      cli_config:
        config: "{{ lookup('template', 'port-forwards.j2') }}"

    - name: Set firewalls
      cli_config:
        config: "{{ lookup('template', 'firewall.j2') }}"

    - name: Define vlans
      cli_config:
        config: "{{ lookup('template', 'vlans.j2') }}"
